name: Build LaTeX document
on:
  push:
  pull_request:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile debug LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: open-logic-debug.tex
          latexmk_use_lualatex: true
          extra_system_packages: fonts-noto-cjk
      - name: Upload open-logic-debug.pdf
        uses: actions/upload-artifact@master
        with:
          name: open-logic-debug.pdf
          path: open-logic-debug.pdf
      - name: Compile release LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: open-logic-complete.tex
          latexmk_use_lualatex: true
          extra_system_packages: fonts-noto-cjk
      - name: Upload open-logic-complete.pdf
        uses: actions/upload-artifact@master
        with:
          name: open-logic-complete.pdf
          path: open-logic-complete.pdf
